### ISSUE TITLE
SSl ERROR

### ISSUE THREAD

**Issue by muratgoren** [pinokiocomputer/pinokio#886]
I got ssl error

self.load_verify_locations(cadata=certs)
ssl.SSLError: [X509V3: INVALID_CERTIFICATE] invalid certificate (_ssl.c:4030)

**Comment by rock5917** [comment]
It would be nice if the errors we see at CLI could say something like, "Would you kindly disable VPN(also firewall and AV, just in case...).", but they don't. Well, that's how I fixed this issue*.

*SSL error but with a different number.

**Comment by drejcreative** [comment]
I stopped my antivirus/firewall and VPN and still getting this issue. @rock5917 Can you tell a little more, about which OS you are using, and which services you stopped?
